import type { Metadata } from "next";
import Link from "next/link";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

/**
 * Terms of use.
 *
 * Short and honest, and tied to how the product actually behaves:
 *
 *   • products + prices   — src/lib/payments/index.ts (PRODUCTS)
 *   • pass window         — src/lib/entitlements.ts (PASS_DAYS = 30)
 *   • never revoking work — src/lib/entitlements.ts (a lapsed pass does not
 *                           take back anything already downloaded)
 *   • reference images    — src/lib/pinterest.ts (fetched from Pinterest, not
 *                           licensed to us or to the user)
 */

export const metadata: Metadata = {
  title: { absolute: "Terms of Use | Fills" },
  description:
    "The terms for using Fills: what a generated brief is and isn't, who owns the reference images, and how buying a brief or a project pass works.",
  alternates: { canonical: "https://fills.io/terms" },
  openGraph: {
    type: "website",
    url: "https://fills.io/terms",
    title: "Terms of Use | Fills",
    description:
      "What a generated brief is and isn't, who owns the reference images, and how buying works.",
  },
  twitter: {
    card: "summary_large_image",
    title: "Terms of Use | Fills",
    description:
      "What a generated brief is and isn't, who owns the reference images, and how buying works.",
  },
};

const LAST_UPDATED = "21 August 2026";
/** Shared inbox, not a personal one. See the note in privacy/page.tsx. */
const CONTACT_EMAIL = "hello@fills.io";

const h2 = "font-serif text-[24px] font-medium leading-tight text-txt";
const p = "text-[15px] leading-[1.8] font-light text-txt-2";
const li = "text-[15px] leading-[1.8] font-light text-txt-2";
const link =
  "text-acc underline decoration-acc/40 underline-offset-2 transition hover:decoration-acc";

export default function TermsPage() {
  return (
    <>
      <Navbar />
      <main className="min-h-screen bg-bg px-6 py-16 sm:px-8">
        <div className="mx-auto max-w-[680px]">
          <span className="inline-flex items-center gap-2.5 font-mono text-[9px] font-medium uppercase tracking-[0.18em] text-acc">
            <span className="inline-block h-px w-6 bg-acc" />
            Terms of use
          </span>
          <h1 className="mt-5 font-serif text-[clamp(30px,4.6vw,46px)] font-medium leading-[1.06] tracking-tight text-txt">
            The deal, in plain English.
          </h1>
          <p className={`mt-4 max-w-xl ${p}`}>
            Using Fills means agreeing to what&apos;s on this page. It is short
            on purpose. There is nothing here we&apos;d be embarrassed to say
            out loud.
          </p>
          <p className="mt-3 font-mono text-[10px] uppercase tracking-[0.14em] text-txt-3">
            Last updated · {LAST_UPDATED}
          </p>

          {/* ── What Fills is ─────────────────────────────────────────────── */}
          <section className="mt-12 border-t border-bdr pt-8">
            <h2 className={h2}>What Fills is</h2>
            <p className={`mt-3 ${p}`}>
              Fills turns a short description of a space into a design brief: a
              direction, a palette, materials, lighting and furniture, pulled
              together with reference images. It is a tool for getting from a
              blank page to something you can react to, quickly.
            </p>
          </section>

          {/* ── Not professional advice ───────────────────────────────────── */}
          <section className="mt-14 border-t border-bdr pt-8">
            <h2 className={h2}>A brief is guidance, not professional advice</h2>
            <p className={`mt-3 ${p}`}>
              What Fills gives you is generated by software. It is a starting
              point and a way of thinking about a space. It is not
              professional interior design, architectural, structural,
              engineering, safety or regulatory advice, and it does not replace
              a qualified professional who has seen your actual space.
            </p>
            <p className={`mt-3 ${p}`}>
              Before anyone builds anything, get the practical questions
              answered by someone qualified: structure, fire and safety,
              accessibility, electrical and plumbing, permits, landlord or mall
              guidelines, and whether the materials suggested are appropriate
              and available where you are. Fills doesn&apos;t know your local
              building codes, your budget reality, or what&apos;s behind your
              walls.
            </p>
            <p className={`mt-3 ${p}`}>
              A brief may also simply be wrong. Generated text can be confidently
              inaccurate, suggest a material that doesn&apos;t suit the use, or
              propose something that won&apos;t fit. Read it with judgement, the
              way you would a keen junior&apos;s first draft. If you want a human
              eye on it,{" "}
              <Link href="/talk-to-a-designer" className={link}>
                talk to a designer
              </Link>
              .
            </p>
          </section>

          {/* ── Reference images ──────────────────────────────────────────── */}
          <section className="mt-14 border-t border-bdr pt-8">
            <h2 className={h2}>The reference images aren&apos;t ours</h2>
            <p className={`mt-3 ${p}`}>
              The photographs in a brief are found on Pinterest and shown to
              communicate a direction: this kind of light, that kind of
              texture. They belong to the photographers, designers, studios and
              brands who made them. Neither we nor you own them.
            </p>
            <p className={`mt-3 ${p}`}>
              So: use them as inspiration and to show a client what you mean.
              Don&apos;t treat them as licensed stock, don&apos;t republish or
              sell them, and don&apos;t present them as your own work or as
              photographs of a space you designed. If you want an image for
              anything beyond internal reference, license it from whoever owns
              it. Tell us at{" "}
              <a href={`mailto:${CONTACT_EMAIL}`} className={link}>
                {CONTACT_EMAIL}
              </a>{" "}
              if your image is in a brief and you&apos;d like it removed.
            </p>
            <p className={`mt-3 ${p}`}>
              The written brief itself, meaning the direction, the palette and
              the notes, is yours to use for your project, including
              commercially.
            </p>
          </section>

          {/* ── No guarantee ──────────────────────────────────────────────── */}
          <section className="mt-14 border-t border-bdr pt-8">
            <h2 className={h2}>No guarantee it&apos;s right for you</h2>
            <p className={`mt-3 ${p}`}>
              Fills is provided as it is. We don&apos;t promise a brief will
              suit your space, your budget, your timeline or your taste, that it
              will be accurate, or that the site will be available and working
              at any given moment. This is an early product that changes often.
            </p>
            <p className={`mt-3 ${p}`}>
              Decisions you make off the back of a brief are yours. To the
              fullest extent the law allows, we&apos;re not liable for costs,
              delays, construction problems or losses that follow from using it,
              and if we ever are held liable for something, it&apos;s limited to
              what you paid us.
            </p>
            <p className={`mt-3 ${p}`}>
              Nothing here takes away rights you have by law as a consumer.
            </p>
          </section>

          {/* ── Buying ────────────────────────────────────────────────────── */}
          <section className="mt-14 border-t border-bdr pt-8">
            <h2 className={h2}>Buying, and what you get to keep</h2>
            <p className={`mt-3 ${p}`}>
              Building a brief is free. Downloading the finished deck is what
              you pay for, and there are two ways to do it:
            </p>
            <ul className="mt-4 space-y-3">
              <li className={li}>
                <span className="text-txt">A single brief.</span> You buy that
                one deck outright. It never expires and it is never taken back.
                You own it.
              </li>
              <li className={li}>
                <span className="text-txt">A project pass.</span> Covers every
                brief you make for 30 days from purchase. When the 30 days are
                up, the pass stops unlocking new downloads.
              </li>
            </ul>
            <p className={`mt-3 ${p}`}>
              Here is the part worth saying explicitly:{" "}
              <span className="text-txt">
                anything you have already downloaded stays yours, permanently.
              </span>{" "}
              A pass running out doesn&apos;t claw back the decks you made while
              it was live, and it doesn&apos;t stop you reading briefs you have
              already generated. Holding your finished work hostage isn&apos;t
              something we&apos;re willing to do.
            </p>
            <p className={`mt-3 ${p}`}>
              Prices are shown at checkout in US dollars and may change over
              time; what you paid is what your receipt records. Purchases are
              tied to the email address you use at checkout, which is how we
              recognise you when you come back. There&apos;s no account to
              create.
            </p>
            <p className={`mt-3 ${p}`}>
              <span className="text-txt">Refunds.</span> If a brief fails to
              generate, arrives broken, or you were charged for something you
              didn&apos;t receive, email{" "}
              <a href={`mailto:${CONTACT_EMAIL}`} className={link}>
                {CONTACT_EMAIL}
              </a>{" "}
              and we&apos;ll refund you. A refund ends the access it paid for,
              but, as above, it doesn&apos;t reach into your computer and take
              back a file you already have. Since a brief is delivered
              immediately, we can&apos;t generally refund one simply because you
              changed your mind about the direction it suggested.
            </p>
            <p className={`mt-3 ${p}`}>
              At the time of writing, paid checkout is not switched on yet.
            </p>
          </section>

          {/* ── Fair use ──────────────────────────────────────────────────── */}
          <section className="mt-14 border-t border-bdr pt-8">
            <h2 className={h2}>Using it fairly</h2>
            <p className={`mt-3 ${p}`}>
              Every brief costs us real money to produce, so there are limits on
              how fast the generation and image search can be called. Please
              don&apos;t script the product, scrape it, resell access to it, or
              try to get around those limits. Don&apos;t use Fills for anything
              illegal, and don&apos;t put anything into the description box that
              you don&apos;t have the right to share. We may cut off access that
              is causing harm or running up costs.
            </p>
          </section>

          {/* ── Changes ───────────────────────────────────────────────────── */}
          <section className="mt-14 border-t border-bdr pt-8">
            <h2 className={h2}>Changes to these terms</h2>
            <p className={`mt-3 ${p}`}>
              Fills is a work in progress, and these terms will move as the
              product does. The date at the top says when they last changed.
              Anything you already bought is governed by the terms as they stood
              when you bought it.
            </p>
            <p className={`mt-3 ${p}`}>
              How we handle your data is covered separately, in our{" "}
              <Link href="/privacy" className={link}>
                privacy policy
              </Link>
              . Questions about either page go to{" "}
              <a href={`mailto:${CONTACT_EMAIL}`} className={link}>
                {CONTACT_EMAIL}
              </a>
              .
            </p>
          </section>
        </div>
      </main>
      <Footer />
    </>
  );
}
